# Generated by Django 5.1.3 on 2024-12-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cute_paccho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="faq_logging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FaqTitle", models.CharField(max_length=10)),
                ("CompanyName", models.CharField(max_length=20)),
                ("Name", models.CharField(max_length=10)),
                ("TelephoneNumber", models.CharField(max_length=15)),
                ("MailAddress", models.CharField(max_length=30)),
                ("InputDate", models.DateField(auto_now_add=True)),
                ("Massage", models.CharField(max_length=200)),
            ],
        ),
    ]
