# Generated by Django 5.1.3 on 2024-12-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cute_paccho", "0002_faq_logging"),
    ]

    operations = [
        migrations.CreateModel(
            name="calc_conduit_size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CulcSerial", models.CharField(max_length=10)),
                ("CableName", models.CharField(max_length=10)),
                ("CableNumber", models.CharField(max_length=10)),
            ],
        ),
    ]
